### ISSUE TITLE
add environment as a config source

### ISSUE THREAD

**Issue by patrickhuber** [patrickhuber/wrangle#13]
add a config source that reads from the environment and sets variables from those values. 

```
config-sources:
- name: environment
  type: env
  params:
    my_var: MY_ENV_VAR
```
