### ISSUE TITLE
exluding the sources config section causes print-env to panic

### ISSUE THREAD

**Issue by patrickhuber** [patrickhuber/wrangle#20]
The following config causes a panic when print-env is called:

```
---
environments:
- name: lab
  processes:
  - name: echo
    path: echo
    stores: [ store1 ]
    env:
      WRANGLE_TEST: hello
```
