### ISSUE TITLE
add `ensure` property to stores where a store will write in values if they don't exist

### ISSUE THREAD

**Issue by patrickhuber** [patrickhuber/wrangle#22]
For example, when setting up credhub for concourse, the author of a pipeline needs several credentials to be inserted like `opsman_username` and `opsman_password` these often exist in other stores. 

The ensure property would contain a list of secrets with the same structure as this: https://credhub-api.cfapps.io/#set-credentials

CredHub is the only store where these types matter, all other stores would just write them out as a hierarchy value type or json type. 

a very contrived and inaccurate example could be:

```
stores:
- name: environment
  type: env
  params:
    control_plane: CONTROL_PLANE
    environment: ENVIRONMENT

- name: bosh-control-plane
  stores: [environment]
  param:
    path: /path/to/vars/store/((control_plane)).yml

- name: bosh-vars-store
  stores: [environment]
  param:
    path: /path/to/vars/store/((environment)).yml

- name: bosh-credhub
  stores: [environment]
  param:
    client_id: ((credhub_client))
    client_secret: ((credhub_secret))
    server: ((credhub_server))
    ca_cert: ((credhub_ca.certificate))
    
- name: concourse-credhub
  stores: [bosh-credhub, bosh-vars-store]
  param:    
    client_id: ((/bosh-1/credhub_client))
    client_secret: ((/bosh-1/credhub_secret))
    server: ((/bosh-1/credhub_server))
    ca_cert: ((/bosh-1/credhub_ca.certificate))
  ensure:
    - name: /concourse/ops_man
      type: user
      value: 
         username: ((/opsman_id))
         password: ((/opsman_password))       
```
