### ISSUE TITLE
enhance package management

### ISSUE THREAD

**Issue by patrickhuber** [patrickhuber/wrangle#25]
Allow for listing multiple versions
Allow for latest tag
Allow for installing specific version
Allow for remote repository list
Allow for synching with remote

**Comment by patrickhuber** [comment]
```yaml
packages:
- name: fly
  versions:
  - name: 3.14.1
    platforms:
    - name: linux
      
```
