### ISSUE TITLE
investigate adding environment support to stores

### ISSUE THREAD

**Issue by patrickhuber** [patrickhuber/wrangle#27]
Looking to consolidate a config store so that it can be reused instead of being a one off for each environment. 

For example, a control plane would have:
1. a bosh director creds file
2. a bosh director credhub
3. a concourse credhub

If there are two of these, there would be 6 total configurations. 

It would be nice to represent the structure once and allow for parameterization based on any variables passed in. For example, region and environment.

**Comment by patrickhuber** [comment]
### Current State

Currently the representation of a store is as follows

```
stores:
- name: bosh-yaml
  type: file
  params:
    path: state/vars/director-vars-store.yml
```

### Suggestion one: Stores as
