### ISSUE TITLE
add list and get methods for config stores

### ISSUE THREAD

**Issue by patrickhuber** [patrickhuber/wrangle#29]
As a user of wrangle
I would like to list and get individual config items
So that I can easily discover configuration without leaving the cli. 

#### list

```
wrangle list [command options] <config store>/[path]

command options:
-r, --recursive            recursively list out all items in path
-f, --format               select the format (yaml|json|tree|xml)
```

```
wrangle list -r bosh-yaml/concourse
```

```
concourse:
  create-pcf:
    om_host:
    om_password:
    vcenter_user:
```

#### get

```
wrangle get [command options] <config store>/<path>
```

```

```
