### ISSUE TITLE
add proxies node for config

### ISSUE THREAD

**Issue by patrickhuber** [patrickhuber/wrangle#35]
Instead of trying to setup a store for ssh and http proxies, instead create proxies as first class citizens. 

```
proxies:
- name: jumpbox
  type: ssh
  params:
    remote:
      host: 10.0.0.10
      port: 2222
    local: 
      host: localhost
      port: 5000
```
